### ISSUE TITLE
Bower registration

### ISSUE THREAD

**Issue by twigbranch** [iDoRecall/selectionmenu#6]
$ bower install selection-menu
ENOTFOUND Package selection-menu not found

**Comment by dandv** [comment]
Would it be possible to use npm?

See https://www.quora.com/Why-use-Bower-when-there-is-npm and http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool. We haven't yet found a good use case for bower, grunt, or gulp, where npm wouldn't suffice.

**Comment by twigbranch** [comment]
cant say its not possible, but it would certainly be inconvenient at this point.

as a library developer it would seem to make sense for you to support popular package managers. bower is certainly one.  while the author of that most upvoted answer on quora saw no value in using bower over npm for his setup in his answer, he agreed in comments that jquery plugin authors only publishing to bower and not npm was a reasonable point.  

i use bower. a lot of others use bower. your library is small, focused on front end, plays nicely with jquery. it would make sense to integrate seemlessly with the popular front end package managers.
